# Generated by Django 3.2.19 on 2024-04-07 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('text', models.CharField(max_length=30, verbose_name='Text')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Value')),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Apartment Number')),
                ('name', models.CharField(max_length=30, verbose_name='Apartment Name')),
                ('street', models.CharField(max_length=30, verbose_name='Street')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Postal Code')),
                ('city', models.CharField(max_length=30, verbose_name='City')),
                ('size_in_m2', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Size in Square Meters')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=27, verbose_name='Booking Text')),
                ('date', models.DateField(verbose_name='Date')),
                ('bill_number', models.CharField(max_length=15, verbose_name='Bill number')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Value')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumptionCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('argument1_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Argument 1 Value')),
                ('operator1', models.CharField(blank=True, choices=[('+', '+'), ('-', '-'), ('*', '*'), ('/', '/'), (' ', ' ')], max_length=1, null=True, verbose_name='Operator 1')),
                ('argument2_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Argument 2 Value')),
                ('operator2', models.CharField(blank=True, choices=[('+', '+'), ('-', '-'), ('*', '*'), ('/', '/'), (' ', ' ')], max_length=1, null=True, verbose_name='Operator 2')),
                ('argument3_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Argument 3 Value')),
            ],
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=27, verbose_name='Cost Center Text')),
                ('is_oiltank', models.BooleanField(verbose_name='Is Oiltank')),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(max_length=40, verbose_name='Remark')),
                ('meter_number', models.CharField(max_length=30, verbose_name='Meter Number')),
                ('build_in_date', models.DateField(verbose_name='Build-in Date')),
                ('out_of_order_date', models.DateField(blank=True, null=True, verbose_name='Out of Order Date')),
            ],
        ),
        migrations.CreateModel(
            name='MeterPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EL', 'electricity'), ('GA', 'gas'), ('KW', 'cold water'), ('WW', 'warm water'), ('HE', 'heating'), ('OI', 'fuel oil')], max_length=2, verbose_name='Meter Type')),
                ('name', models.CharField(max_length=50, verbose_name='Name of the Meter Place')),
                ('remark', models.CharField(blank=True, default='', max_length=40, verbose_name='Remark')),
                ('location', models.CharField(default='', max_length=200, verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('alt_street', models.CharField(blank=True, max_length=30, null=True, verbose_name='Alternative Street')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Postal Code')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='City')),
                ('move_in_date', models.DateField(verbose_name='Move in on date')),
                ('move_out_date', models.DateField(blank=True, null=True, verbose_name='Move out date')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.apartment', verbose_name='Apartment')),
            ],
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('meter_reading', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Meter Reading')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.meter', verbose_name='Meter')),
            ],
        ),
        migrations.AddField(
            model_name='meter',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.meterplace', verbose_name='Meter Place'),
        ),
        migrations.CreateModel(
            name='CostCenterContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appartment', to='bill.apartment', verbose_name='Apartment')),
                ('consumption_calc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_calc', to='bill.consumptioncalc', verbose_name='Consumption')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.costcenter', verbose_name='Cost Center')),
            ],
        ),
        migrations.CreateModel(
            name='CostCenterBillEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oil_in_liter', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='Oil in Liter')),
                ('account_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.accountentry', verbose_name='Account Entry')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.costcenter', verbose_name='Cost Center')),
            ],
        ),
        migrations.AddField(
            model_name='consumptioncalc',
            name='argument1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arg1', to='bill.meterplace', verbose_name='Argument 1'),
        ),
        migrations.AddField(
            model_name='consumptioncalc',
            name='argument2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arg2', to='bill.meterplace', verbose_name='Argument 2'),
        ),
        migrations.AddField(
            model_name='consumptioncalc',
            name='argument3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arg3', to='bill.meterplace', verbose_name='Argument 3'),
        ),
        migrations.AddField(
            model_name='accountentry',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bill.bill', verbose_name='Bill'),
        ),
    ]
