# Generated by Django 5.2.9 on 2025-12-15 09:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=27, verbose_name='Account Period Name')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Apartment Number')),
                ('name', models.CharField(max_length=30, verbose_name='Apartment Name')),
                ('street', models.CharField(max_length=30, verbose_name='Street')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Postal Code')),
                ('city', models.CharField(max_length=30, verbose_name='City')),
                ('size_in_m2', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Size in Square Meters')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumptionCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('argument1_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Argument 1 Value')),
                ('operator1', models.CharField(blank=True, choices=[('+', '+'), ('-', '-'), ('*', '*'), ('/', '/'), (' ', ' ')], max_length=1, null=True, verbose_name='Operator 1')),
                ('argument2_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Argument 2 Value')),
                ('operator2', models.CharField(blank=True, choices=[('+', '+'), ('-', '-'), ('*', '*'), ('/', '/'), (' ', ' ')], max_length=1, null=True, verbose_name='Operator 2')),
                ('argument3_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Argument 3 Value')),
            ],
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=27, verbose_name='Cost Center Text')),
                ('is_oiltank', models.BooleanField(verbose_name='Is Oiltank')),
            ],
        ),
        migrations.CreateModel(
            name='MeterPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EL', 'electricity'), ('GA', 'gas'), ('KW', 'cold water'), ('WW', 'warm water'), ('HE', 'heating'), ('OI', 'fuel oil')], max_length=2, verbose_name='Meter Type')),
                ('name', models.CharField(max_length=50, verbose_name='Name of the Meter Place')),
                ('remark', models.CharField(blank=True, default='', max_length=40, verbose_name='Remark')),
                ('location', models.CharField(default='', max_length=200, verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=40, verbose_name='Booking Text')),
                ('bill_date', models.DateField(verbose_name='Date')),
                ('bill_number', models.CharField(max_length=20, verbose_name='Bill number')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Value')),
                ('from_date', models.DateField(verbose_name='From Date')),
                ('to_date', models.DateField(verbose_name='To Date')),
                ('account_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.accountperiod', verbose_name='Account Period')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.costcenter', verbose_name='Cost Center')),
            ],
        ),
        migrations.CreateModel(
            name='AccountEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('text', models.CharField(max_length=30, verbose_name='Text')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Value')),
                ('account_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.accountperiod', verbose_name='Account Period')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.bill', verbose_name='Bill')),
            ],
        ),
        migrations.CreateModel(
            name='CostCenterBillEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oil_in_liter', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='Oil in Liter')),
                ('account_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.accountentry', verbose_name='Account Entry')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.costcenter', verbose_name='Cost Center')),
            ],
        ),
        migrations.CreateModel(
            name='CostCenterContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appartment', to='bill.apartment', verbose_name='Apartment')),
                ('consumption_calc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_calc', to='bill.consumptioncalc', verbose_name='Consumption')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.costcenter', verbose_name='Cost Center')),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(blank=True, default='', max_length=40, verbose_name='Remark')),
                ('meter_number', models.CharField(max_length=30, verbose_name='Meter Number')),
                ('build_in_date', models.DateField(verbose_name='Build-in Date')),
                ('calibrated_until_date', models.DateField(verbose_name='Calibrated until')),
                ('out_of_order_date', models.DateField(blank=True, null=True, verbose_name='Out of Order Date')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.meterplace', verbose_name='Meter Place')),
            ],
        ),
        migrations.AddField(
            model_name='consumptioncalc',
            name='argument1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arg1', to='bill.meterplace', verbose_name='Argument 1'),
        ),
        migrations.AddField(
            model_name='consumptioncalc',
            name='argument2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arg2', to='bill.meterplace', verbose_name='Argument 2'),
        ),
        migrations.AddField(
            model_name='consumptioncalc',
            name='argument3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arg3', to='bill.meterplace', verbose_name='Argument 3'),
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Time')),
                ('meter_reading', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Meter Reading')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.meter', verbose_name='Meter')),
            ],
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('alt_street', models.CharField(blank=True, max_length=30, null=True, verbose_name='Alternative Street')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Postal Code')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='City')),
                ('move_in_date', models.DateField(verbose_name='Move in on date')),
                ('move_out_date', models.DateField(blank=True, null=True, verbose_name='Move out date')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.apartment', verbose_name='Apartment')),
            ],
        ),
        migrations.CreateModel(
            name='HeatingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2023), django.core.validators.MaxValueValidator(2300)])),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('heating_energy_kwh', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='Heating energy')),
                ('compare_heating_energy_kwh', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='Compare Heating energy')),
                ('hot_water_energy_kwh', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='Hot water energy')),
                ('compare_hot_water_energy_kwh', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='Compare hot water energy')),
                ('hot_water_m3', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='Hot water m3')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.apartment', verbose_name='Appartment')),
            ],
            options={
                'indexes': [models.Index(fields=['apartment', 'year', 'month'], name='bill_heatin_apartme_8b74dd_idx')],
                'constraints': [models.UniqueConstraint(fields=('apartment', 'year', 'month'), name='unique_rentrecord_per_apartment_per_month')],
            },
        ),
        migrations.CreateModel(
            name='HeatingInfoTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2023), django.core.validators.MaxValueValidator(2300)])),
                ('next_month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('kwh_per_m3_hot_water', models.FloatField()),
                ('compare_heating_group', models.IntegerField()),
                ('compare_hot_water_group', models.IntegerField()),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.apartment', verbose_name='Appartment')),
                ('calc_heating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calc_heating', to='bill.consumptioncalc', verbose_name='Consumption Heating')),
                ('calc_hot_water', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calc_hot_water', to='bill.consumptioncalc', verbose_name='Consumption Hot Water')),
            ],
            options={
                'indexes': [models.Index(fields=['apartment'], name='bill_heatin_apartme_f92152_idx')],
                'constraints': [models.UniqueConstraint(fields=('apartment',), name='unique_rentrecord_per_apartment')],
            },
        ),
        migrations.AddConstraint(
            model_name='meter',
            constraint=models.CheckConstraint(condition=models.Q(('out_of_order_date__gt', models.F('build_in_date')), ('out_of_order_date__isnull', True), _connector='OR'), name='check_build_in_before_out_of_order'),
        ),
        migrations.AddConstraint(
            model_name='meter',
            constraint=models.UniqueConstraint(condition=models.Q(('out_of_order_date__isnull', True)), fields=('place',), name='unique_active_meter_per_place'),
        ),
        migrations.AddConstraint(
            model_name='meterreading',
            constraint=models.UniqueConstraint(fields=('meter', 'date'), name='unique_meter_reading_per_day'),
        ),
    ]
