# Generated by Django 5.2.9 on 2025-12-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='remote_address',
            field=models.CharField(blank=True, default='', help_text='Address/ID for remote reading (e.g. M-Bus serial, IP address, API endpoint)', max_length=200, verbose_name='Remote Address'),
        ),
        migrations.AddField(
            model_name='meter',
            name='remote_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('mbus', 'M-Bus'), ('modbus', 'Modbus'), ('http', 'HTTP API'), ('mqtt', 'MQTT')], default='manual', max_length=10, verbose_name='Remote Type'),
        ),
    ]
