# Generated by Django 3.2.19 on 2024-04-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Remark'),
        ),
    ]
