# Generated by Django 3.2.19 on 2024-04-07 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_alter_meter_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountentry',
            name='bill',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bill.bill', verbose_name='Bill'),
            preserve_default=False,
        ),
    ]
