# Generated by Django 5.2.9 on 2025-12-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_meter_remote_address_meter_remote_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumptioncalc',
            name='argument1_explanation',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Argument 1 Explanation'),
        ),
        migrations.AddField(
            model_name='consumptioncalc',
            name='argument1_unit',
            field=models.CharField(blank=True, choices=[('', ''), ('kWh', 'kWh'), ('m³', 'm³'), ('Liter', 'Liter'), ('m²', 'm²'), ('%', '%')], default='', max_length=10, verbose_name='Argument 1 Unit'),
        ),
        migrations.AddField(
            model_name='consumptioncalc',
            name='argument2_explanation',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Argument 2 Explanation'),
        ),
        migrations.AddField(
            model_name='consumptioncalc',
            name='argument2_unit',
            field=models.CharField(blank=True, choices=[('', ''), ('kWh', 'kWh'), ('m³', 'm³'), ('Liter', 'Liter'), ('m²', 'm²'), ('%', '%')], default='', max_length=10, verbose_name='Argument 2 Unit'),
        ),
        migrations.AddField(
            model_name='consumptioncalc',
            name='argument3_explanation',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Argument 3 Explanation'),
        ),
        migrations.AddField(
            model_name='consumptioncalc',
            name='argument3_unit',
            field=models.CharField(blank=True, choices=[('', ''), ('kWh', 'kWh'), ('m³', 'm³'), ('Liter', 'Liter'), ('m²', 'm²'), ('%', '%')], default='', max_length=10, verbose_name='Argument 3 Unit'),
        ),
    ]
