# Generated by Django 5.2.9 on 2025-12-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_consumptioncalc_argument1_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcentercontribution',
            name='special_designation',
            field=models.CharField(blank=True, default='', help_text="Alternative designation when no apartment is selected (e.g. 'Washing Machine Counter')", max_length=100, verbose_name='Special Designation'),
        ),
        migrations.AddConstraint(
            model_name='costcentercontribution',
            constraint=models.CheckConstraint(condition=models.Q(('apartment__isnull', False), ('special_designation__gt', ''), _connector='OR'), name='apartment_or_special_designation_required', violation_error_message='Either apartment or special designation must be provided'),
        ),
    ]
