# Generated by Django 5.0.3 on 2024-07-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bill", "0003_alter_accountentry_bill"),
    ]

    operations = [
        migrations.AddField(
            model_name="meter",
            name="calibrated_until_date",
            field=models.DateField(default='2000-01-01',
                                   verbose_name="Calibrated until"),
            preserve_default=False,
        ),
    ]
