# Generated by Django 5.0.3 on 2024-07-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bill", "0004_meter_calibrated_until_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="text",
            field=models.CharField(max_length=40, verbose_name="Booking Text"),
        ),
    ]
