# Generated by Django 4.2 on 2025-12-31

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0004_costcentercontribution_special_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumptioncalc',
            name='start_date',
            field=models.DateField(default=datetime.date(
                2020, 1, 1), verbose_name='Start Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consumptioncalc',
            name='end_date',
            field=models.DateField(blank=True, null=True,
                                   verbose_name='End Date'),
        ),
    ]
