# Generated by Django 5.0.7 on 2024-07-21 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bill", "0005_alter_bill_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(max_length=27, verbose_name="Account Period Name"),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("end_date", models.DateField(verbose_name="End Date")),
            ],
        ),
        migrations.AddField(
            model_name="accountentry",
            name="account_period",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="bill.accountperiod",
                verbose_name="Account Period",
            ),
            preserve_default=False,
        ),
    ]
