# Generated by Django 5.2.9 on 2025-12-31 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0005_consumptioncalc_start_date_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumptioncalc',
            name='operator',
            field=models.CharField(choices=[('+', '+'), ('-', '-'), ('*', '*'), ('/', '/'), (' ', ' ')], default='+', help_text='Operator, der alle Argumente verknüpft', max_length=1, verbose_name='Operator'),
        ),
        migrations.AlterField(
            model_name='consumptioncalc',
            name='argument1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arg1', to='bill.meterplace', verbose_name='Argument 1 (DEPRECATED)'),
        ),
        migrations.AlterField(
            model_name='consumptioncalc',
            name='argument1_explanation',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Argument 1 Explanation (DEPRECATED)'),
        ),
        migrations.AlterField(
            model_name='consumptioncalc',
            name='argument1_unit',
            field=models.CharField(blank=True, choices=[('', ''), ('kWh', 'kWh'), ('m³', 'm³'), ('Liter', 'Liter'), ('m²', 'm²'), ('%', '%')], default='', max_length=10, verbose_name='Argument 1 Unit (DEPRECATED)'),
        ),
        migrations.AlterField(
            model_name='consumptioncalc',
            name='argument1_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Argument 1 Value (DEPRECATED)'),
        ),
        migrations.AlterField(
            model_name='consumptioncalc',
            name='argument2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arg2', to='bill.meterplace', verbose_name='Argument 2 (DEPRECATED)'),
        ),
        migrations.AlterField(
            model_name='consumptioncalc',
            name='argument2_explanation',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Argument 2 Explanation (DEPRECATED)'),
        ),
        migrations.AlterField(
            model_name='consumptioncalc',
            name='argument2_unit',
            field=models.CharField(blank=True, choices=[('', ''), ('kWh', 'kWh'), ('m³', 'm³'), ('Liter', 'Liter'), ('m²', 'm²'), ('%', '%')], default='', max_length=10, verbose_name='Argument 2 Unit (DEPRECATED)'),
        ),
        migrations.AlterField(
            model_name='consumptioncalc',
            name='argument2_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Argument 2 Value (DEPRECATED)'),
        ),
        migrations.AlterField(
            model_name='consumptioncalc',
            name='argument3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arg3', to='bill.meterplace', verbose_name='Argument 3 (DEPRECATED)'),
        ),
        migrations.AlterField(
            model_name='consumptioncalc',
            name='argument3_explanation',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Argument 3 Explanation (DEPRECATED)'),
        ),
        migrations.AlterField(
            model_name='consumptioncalc',
            name='argument3_unit',
            field=models.CharField(blank=True, choices=[('', ''), ('kWh', 'kWh'), ('m³', 'm³'), ('Liter', 'Liter'), ('m²', 'm²'), ('%', '%')], default='', max_length=10, verbose_name='Argument 3 Unit (DEPRECATED)'),
        ),
        migrations.AlterField(
            model_name='consumptioncalc',
            name='argument3_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Argument 3 Value (DEPRECATED)'),
        ),
        migrations.AlterField(
            model_name='consumptioncalc',
            name='operator1',
            field=models.CharField(blank=True, choices=[('+', '+'), ('-', '-'), ('*', '*'), ('/', '/'), (' ', ' ')], max_length=1, null=True, verbose_name='Operator 1 (DEPRECATED)'),
        ),
        migrations.AlterField(
            model_name='consumptioncalc',
            name='operator2',
            field=models.CharField(blank=True, choices=[('+', '+'), ('-', '-'), ('*', '*'), ('/', '/'), (' ', ' ')], max_length=1, null=True, verbose_name='Operator 2 (DEPRECATED)'),
        ),
        migrations.CreateModel(
            name='ConsumptionCalcArgument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(help_text='Reihenfolge in der Berechnung', verbose_name='Position')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Festwert')),
                ('unit', models.CharField(blank=True, choices=[('', ''), ('kWh', 'kWh'), ('m³', 'm³'), ('Liter', 'Liter'), ('m²', 'm²'), ('%', '%')], default='', max_length=10, verbose_name='Einheit')),
                ('explanation', models.CharField(blank=True, default='', max_length=200, verbose_name='Erklärung')),
                ('consumption_calc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arguments', to='bill.consumptioncalc', verbose_name='Berechnung')),
                ('meter_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bill.meterplace', verbose_name='Zählerplatz')),
                ('nested_calc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_in_arguments', to='bill.consumptioncalc', verbose_name='Verschachtelte Berechnung')),
            ],
            options={
                'verbose_name': 'Berechnungs-Argument',
                'verbose_name_plural': 'Berechnungs-Argumente',
                'ordering': ['position'],
                'unique_together': {('consumption_calc', 'position')},
            },
        ),
    ]
