# Generated by Django 5.1.1 on 2024-10-14 05:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bill", "0006_accountperiod_accountentry_account_period"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeatingInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2023),
                            django.core.validators.MaxValueValidator(2300),
                        ]
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                (
                    "heating_energy_kwh",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=8,
                        null=True,
                        verbose_name="Heating energy",
                    ),
                ),
                (
                    "compare_heating_energy_kwh",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=8,
                        null=True,
                        verbose_name="Compare Heating energy",
                    ),
                ),
                (
                    "hot_water_energy_kwh",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=8,
                        null=True,
                        verbose_name="Hot water energy",
                    ),
                ),
                (
                    "compare_hot_water_energy_kwh",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=8,
                        null=True,
                        verbose_name="Compare hot water energy",
                    ),
                ),
                (
                    "hot_water_m3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=8,
                        null=True,
                        verbose_name="Hot water m3",
                    ),
                ),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bill.apartment",
                        verbose_name="Appartment",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["apartment", "year", "month"],
                        name="bill_heatin_apartme_8b74dd_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("apartment", "year", "month"),
                        name="unique_rentrecord_per_apartment_per_month",
                    )
                ],
            },
        ),
    ]
