# Generated by Django 5.1.1 on 2024-10-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bill", "0007_heatinginfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="meterreading",
            name="time",
            field=models.TimeField(blank=True, null=True, verbose_name="Time"),
        ),
    ]
