# Generated by Django 5.2.9 on 2025-12-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0007_migrate_to_arguments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumptioncalc',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
