# Generated by Django 5.1.1 on 2024-10-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bill", "0008_meterreading_time"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="meter",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("out_of_order_date__gt", models.F("build_in_date")),
                    ("out_of_order_date__isnull", True),
                    _connector="OR",
                ),
                name="check_build_in_before_out_of_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="meter",
            constraint=models.UniqueConstraint(
                condition=models.Q(("out_of_order_date__isnull", True)),
                fields=("place",),
                name="unique_active_meter_per_place",
            ),
        ),
    ]
