# Generated by Django 5.2.9 on 2026-01-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0008_alter_consumptioncalc_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='renter',
            name='is_owner_occupied',
            field=models.BooleanField(default=False, help_text='Check if this unit is occupied by the owner or family members. These are not considered rental income for tax purposes.', verbose_name='Owner occupied'),
        ),
    ]
