# Generated by Django 5.2.9 on 2026-01-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0009_add_owner_occupied_to_renter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='size_in_m2',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Size in Square Meters'),
        ),
    ]
