# Generated by Django 5.1.1 on 2024-10-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bill", "0009_meter_check_build_in_before_out_of_order_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="meterreading",
            constraint=models.UniqueConstraint(
                fields=("meter", "date"), name="unique_meter_reading_per_day"
            ),
        ),
    ]
