# Generated by Django 5.1.1 on 2024-10-31 11:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bill", "0010_meterreading_unique_meter_reading_per_day"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeatingInfoTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "next_year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2023),
                            django.core.validators.MaxValueValidator(2300),
                        ]
                    ),
                ),
                (
                    "next_month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("kwh_per_liter_hot_water", models.FloatField()),
                ("compare_heating_group", models.IntegerField()),
                ("compare_hot_water_group", models.IntegerField()),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bill.apartment",
                        verbose_name="Appartment",
                    ),
                ),
                (
                    "calc_heating",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calc_heating",
                        to="bill.consumptioncalc",
                        verbose_name="Consumption Heating",
                    ),
                ),
                (
                    "calc_hot_water",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calc_hot_water",
                        to="bill.consumptioncalc",
                        verbose_name="Consumption Hot Water",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["apartment"], name="bill_heatin_apartme_f92152_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("apartment",), name="unique_rentrecord_per_apartment"
                    )
                ],
            },
        ),
    ]
