# Generated by Django 5.2.9 on 2026-01-03 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0010_alter_apartment_size_in_m2'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcenter',
            name='distribution_type',
            field=models.CharField(choices=[('CONSUMPTION', 'Consumption based (meter reading)'), ('TIME', 'By time (days)'), ('AREA', 'By area (m²)'), ('DIRECT', 'Direct assignment (bill period = renter)')], default='CONSUMPTION', help_text='CONSUMPTION: by meter, TIME: by days, AREA: by m², DIRECT: bill goes to renter in bill period', max_length=20, verbose_name='Distribution Type'),
        ),
        migrations.AlterField(
            model_name='costcentercontribution',
            name='consumption_calc',
            field=models.ForeignKey(blank=True, help_text='Required for consumption-based distribution', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_calc', to='bill.consumptioncalc', verbose_name='Consumption Calculation'),
        ),
    ]
