# Generated by Django 5.2.9 on 2026-01-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0011_add_distribution_type_to_costcenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreading',
            name='auto_reading',
            field=models.BooleanField(default=False, help_text='Indicates if the reading was automatically obtained (e.g., via M-Bus)', verbose_name='Automatic Reading'),
        ),
    ]
