# Generated by Django 5.1.1 on 2024-10-31 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bill", "0011_heatinginfotemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heatinginfotemplate",
            name="calc_heating",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calc_heating",
                to="bill.consumptioncalc",
                verbose_name="Consumption Heating",
            ),
        ),
        migrations.AlterField(
            model_name="heatinginfotemplate",
            name="calc_hot_water",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calc_hot_water",
                to="bill.consumptioncalc",
                verbose_name="Consumption Hot Water",
            ),
        ),
    ]
