# Generated by Django 5.2.9 on 2026-01-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0012_add_auto_reading_to_meter_reading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='meter_reading',
            field=models.DecimalField(decimal_places=3, max_digits=16, verbose_name='Meter Reading'),
        ),
    ]
