# Generated by Django 5.1.1 on 2024-11-03 11:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bill", "0012_alter_heatinginfotemplate_calc_heating_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="heatinginfotemplate",
            old_name="kwh_per_liter_hot_water",
            new_name="kwh_per_m3_hot_water",
        ),
    ]
