# Generated by Django 5.1.1 on 2025-12-07 10:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0013_rename_kwh_per_liter_hot_water_heatinginfotemplate_kwh_per_m3_hot_water'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='date',
            new_name='bill_date',
        ),
        migrations.AddField(
            model_name='bill',
            name='from_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='From Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='to_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='To Date'),
            preserve_default=False,
        ),
    ]
