# Generated by Django 5.2.9 on 2026-01-04 15:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0013_alter_meterreading_meter_reading'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, help_text='Leave empty if still active', null=True, verbose_name='End Date')),
                ('cold_rent', models.DecimalField(decimal_places=2, help_text='Monthly cold rent in EUR', max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cold Rent')),
                ('advance_payment', models.DecimalField(decimal_places=2, help_text='Monthly advance payment for utilities in EUR', max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Advance Payment')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_payments', to='bill.renter', verbose_name='Renter')),
            ],
            options={
                'verbose_name': 'Rent Payment',
                'verbose_name_plural': 'Rent Payments',
                'ordering': ['-start_date'],
            },
        ),
    ]
