# Generated by Django 5.1.1 on 2025-12-07 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0014_rename_date_bill_bill_date_bill_from_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='account_period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bill.accountperiod', verbose_name='Account Period'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='cost_center',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bill.costcenter', verbose_name='Cost Center'),
            preserve_default=False,
        ),
    ]
