# Generated by Django 5.2.9 on 2026-01-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0015_add_landlord_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='property_name',
            field=models.CharField(blank=True, help_text='z.B. Hausverwaltung Haubr.Bahnhofstr.5+7', max_length=100, null=True, verbose_name='Property Name'),
        ),
    ]
