# Generated by Django 5.1.1 on 2025-12-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0015_bill_account_period_bill_cost_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(max_length=20, verbose_name='Bill number'),
        ),
    ]
