# Generated by Django 5.2.9 on 2026-01-04 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0014_add_rent_payment_model'),
        ('bill', '0016_add_property_name_to_landlord'),
    ]

    operations = [
    ]
