# Generated by Django 5.2.9 on 2026-01-05 13:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0017_merge_20260104_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="z.B. 'Mietenkonto', 'Kautionskonto', 'Barkasse'", max_length=100, verbose_name='Account Name')),
                ('account_type', models.CharField(choices=[('BANK', 'Bank Account'), ('CASH', 'Cash Box (Barkasse)')], default='BANK', max_length=4, verbose_name='Account Type')),
                ('iban', models.CharField(blank=True, help_text='Nur für Bankkonten, nicht für Barkasse', max_length=34, null=True, unique=True, verbose_name='IBAN')),
                ('bic', models.CharField(blank=True, max_length=11, null=True, verbose_name='BIC')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Name')),
                ('description', models.TextField(blank=True, help_text='Zusätzliche Informationen zum Konto', null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'ordering': ['account_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MatchingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Beschreibung der Regel (z.B. 'Schwarz via Sozialamt')", max_length=100, verbose_name='Rule Name')),
                ('priority', models.PositiveIntegerField(default=100, help_text='Höher = wird zuerst ausgewertet', verbose_name='Priority')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('match_iban', models.CharField(blank=True, help_text='IBAN des Absenders/Empfängers (exakt)', max_length=34, null=True, verbose_name='Match IBAN')),
                ('match_counterpart_name', models.CharField(blank=True, help_text='Text im Namen des Absenders/Empfängers (contains, case-insensitive)', max_length=200, null=True, verbose_name='Match Counterpart Name')),
                ('match_booking_text', models.CharField(blank=True, help_text='Text im Verwendungszweck (contains, case-insensitive)', max_length=200, null=True, verbose_name='Match Booking Text')),
                ('match_amount_positive', models.BooleanField(blank=True, help_text='True = nur Eingänge, False = nur Ausgänge, None = beide', null=True, verbose_name='Match Amount Direction')),
                ('target_transaction_type', models.CharField(blank=True, choices=[('RENTER', 'Mietertransaktion'), ('EXPENSE', 'Ausgabe'), ('TRANSFER', 'Umbuchung'), ('IGNORE', 'Ignorieren'), ('OTHER', 'Sonstige')], help_text='Transaktionstyp (wenn kein Renter, wird automatisch gesetzt)', max_length=10, null=True, verbose_name='Target Transaction Type')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_renter', models.ForeignKey(blank=True, help_text='Mieter dem zugeordnet werden soll', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matching_rules', to='bill.renter', verbose_name='Target Renter')),
            ],
            options={
                'verbose_name': 'Matching Rule',
                'verbose_name_plural': 'Matching Rules',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(help_text='Buchungsdatum', verbose_name='Booking Date')),
                ('value_date', models.DateField(help_text='Wertstellungsdatum', verbose_name='Value Date')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positiv = Eingang, Negativ = Ausgang', max_digits=10, verbose_name='Amount')),
                ('counterpart_name', models.CharField(blank=True, help_text='Zahlungspflichtiger/Empfänger', max_length=200, null=True, verbose_name='Counterpart Name')),
                ('counterpart_iban', models.CharField(blank=True, max_length=34, null=True, verbose_name='Counterpart IBAN')),
                ('booking_text', models.TextField(help_text='Verwendungszweck', max_length=1000, verbose_name='Booking Text')),
                ('csv_transaction_type', models.CharField(blank=True, help_text="'Eingang'/'Ausgang' aus CSV", max_length=50, null=True, verbose_name='CSV Transaction Type')),
                ('transaction_type', models.CharField(choices=[('RENTER', 'Mietertransaktion'), ('EXPENSE', 'Ausgabe'), ('TRANSFER', 'Umbuchung'), ('IGNORE', 'Ignorieren'), ('OTHER', 'Sonstige')], default='OTHER', max_length=10, verbose_name='Transaction Type')),
                ('is_matched', models.BooleanField(default=False, help_text='Automatisch oder manuell zugeordnet', verbose_name='Matched')),
                ('import_hash', models.CharField(blank=True, help_text='Hash für Duplikat-Erkennung beim Import', max_length=64, null=True, unique=True, verbose_name='Import Hash')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='bill.bankaccount', verbose_name='Bank Account / Cash Box')),
                ('renter', models.ForeignKey(blank=True, help_text='Bei Mieteinnahmen: zugeordneter Mieter', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='bill.renter', verbose_name='Renter')),
                ('matched_by_rule', models.ForeignKey(blank=True, help_text='Die Regel die das Matching durchgeführt hat', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bill.matchingrule', verbose_name='Matched by Rule')),
            ],
            options={
                'verbose_name': 'Bank Transaction',
                'verbose_name_plural': 'Bank Transactions',
                'ordering': ['-booking_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionBillLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Betrag dieser Verknüpfung (Teilzahlung möglich)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount')),
                ('notes', models.CharField(blank=True, help_text="z.B. 'Anzahlung', '2. Rate', 'Teilbetrag'", max_length=200, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_links', to='bill.bill', verbose_name='Bill')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_links', to='bill.banktransaction', verbose_name='Transaction')),
            ],
            options={
                'verbose_name': 'Transaction-Bill Link',
                'verbose_name_plural': 'Transaction-Bill Links',
                'ordering': ['transaction__booking_date'],
            },
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['booking_date'], name='bill_banktr_booking_88e572_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['counterpart_iban'], name='bill_banktr_counter_701f3c_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['renter'], name='bill_banktr_renter__ef138a_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['is_matched'], name='bill_banktr_is_matc_3f5672_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['transaction_type'], name='bill_banktr_transac_e81655_idx'),
        ),
    ]
