# Generated by Django 5.2.9 on 2026-01-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0018_bankaccount_matchingrule_banktransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='paperless_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID des Dokuments in Paperless-NGX', null=True, verbose_name='Paperless ID'),
        ),
    ]
