# Generated by Django 5.2.9 on 2026-01-19 13:09

from django.db import migrations, models


def set_accounting_year_from_value_date(apps, schema_editor):
    """Setze accounting_year aus value_date für alle bestehenden Transaktionen."""
    BankTransaction = apps.get_model('bill', 'BankTransaction')
    for transaction in BankTransaction.objects.filter(accounting_year__isnull=True):
        if transaction.value_date:
            transaction.accounting_year = transaction.value_date.year
            transaction.save(update_fields=['accounting_year'])


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0019_add_paperless_id_to_bill'),
    ]

    operations = [
        # 1. Feld hinzufügen (temporär nullable)
        migrations.AddField(
            model_name='banktransaction',
            name='accounting_year',
            field=models.PositiveSmallIntegerField(
                null=True,
                help_text='Für welches Abrechnungsjahr ist diese Transaktion relevant? Default: Jahr des Wertstellungsdatums',
                verbose_name='Accounting Year'),
        ),
        # 2. Bestehende Daten füllen
        migrations.RunPython(
            set_accounting_year_from_value_date,
            migrations.RunPython.noop,
        ),
        # 3. NOT NULL Constraint setzen
        migrations.AlterField(
            model_name='banktransaction',
            name='accounting_year',
            field=models.PositiveSmallIntegerField(
                help_text='Für welches Abrechnungsjahr ist diese Transaktion relevant? Default: Jahr des Wertstellungsdatums',
                verbose_name='Accounting Year'),
        ),
        # 4. Index hinzufügen
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['accounting_year'], name='bill_banktr_account_a9e537_idx'),
        ),
    ]
