# Generated by Django 5.2.9 on 2026-01-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0020_add_accounting_year_to_banktransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentpayment',
            name='end_date',
            field=models.DateField(blank=True, help_text='Letzter Tag dieser Mietperiode. Leer lassen wenn noch aktiv.', null=True, verbose_name='End Date'),
        ),
        migrations.AddConstraint(
            model_name='rentpayment',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='rent_payment_end_date_after_start_date'),
        ),
    ]
