# Generated by Django 5.2.9 on 2026-01-19 17:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0021_rent_payment_no_overlap_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlyAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Billing Year')),
                ('description', models.CharField(help_text="z.B. 'Schlüssel verloren', 'Streusalz', 'Kaution'", max_length=200, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positiv = Gutschrift für Mieter, Negativ = Abzug', max_digits=10, verbose_name='Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_adjustments', to='bill.renter', verbose_name='Renter')),
            ],
            options={
                'verbose_name': 'Yearly Adjustment',
                'verbose_name_plural': 'Yearly Adjustments',
                'ordering': ['billing_year', 'renter', 'description'],
                'indexes': [models.Index(fields=['billing_year'], name='bill_yearly_billing_9f7e36_idx'), models.Index(fields=['renter'], name='bill_yearly_renter__e651f3_idx')],
            },
        ),
    ]
