# Generated by Django 5.2.9 on 2026-01-24 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0022_add_yearly_adjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcenter',
            name='main_meter_place',
            field=models.ForeignKey(blank=True, help_text='Main meter for consumption-based distribution (used for mid-year tenant changes)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bill.meterplace', verbose_name='Main Meter'),
        ),
    ]
