# Generated by Django 5.2.9 on 2026-01-24 10:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0023_add_main_meter_place_to_costcenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcenter',
            name='area_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Percentage distributed by area (default 30%)', max_digits=5, verbose_name='Area Percentage'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='consumption_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('70.00'), help_text='Percentage distributed by consumption (default 70%)', max_digits=5, verbose_name='Consumption Percentage'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='distribution_type',
            field=models.CharField(choices=[('CONSUMPTION', 'Consumption based (meter reading)'), ('TIME', 'By time (days)'), ('AREA', 'By area (m²)'), ('DIRECT', 'Direct assignment (bill period = renter)'), ('HEATING_MIXED', 'Heating (30% area + 70% consumption)')], default='CONSUMPTION', help_text='CONSUMPTION: by meter, TIME: by days, AREA: by m², DIRECT: bill goes to renter in bill period', max_length=20, verbose_name='Distribution Type'),
        ),
    ]
