# Generated by Django 5.2.9 on 2026-01-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0024_add_heating_mixed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcenter',
            name='distribution_type',
            field=models.CharField(choices=[('CONSUMPTION', 'Consumption based (meter reading)'), ('TIME', 'By time (days)'), ('AREA', 'By area (m²)'), ('DIRECT', 'Direct assignment (bill period = renter)'), ('HEATING_MIXED', 'Heating mixed (area + consumption)')], default='CONSUMPTION', help_text='CONSUMPTION: by meter, TIME: by days, AREA: by m², DIRECT: bill goes to renter in bill period', max_length=20, verbose_name='Distribution Type'),
        ),
    ]
