# Generated by Django 5.2.9 on 2026-01-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0025_alter_costcenter_distribution_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='text',
            field=models.CharField(max_length=60, verbose_name='Booking Text'),
        ),
    ]
