# Generated by Django 5.2.9 on 2026-01-25 08:01

from django.db import migrations, models


def set_contract_dates_from_move_dates(apps, schema_editor):
    """Setze Vertragsdaten auf Einzugs-/Auszugsdatum als Standardwert."""
    Renter = apps.get_model('bill', 'Renter')
    for renter in Renter.objects.all():
        renter.contract_start_date = renter.move_in_date
        renter.contract_end_date = renter.move_out_date
        renter.save(update_fields=['contract_start_date', 'contract_end_date'])


def reverse_contract_dates(apps, schema_editor):
    """Rückgängig machen - Vertragsdaten auf NULL setzen."""
    Renter = apps.get_model('bill', 'Renter')
    Renter.objects.all().update(contract_start_date=None, contract_end_date=None)


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0026_increase_bill_text_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='renter',
            name='contract_end_date',
            field=models.DateField(blank=True, help_text='End date of the rental contract. Defaults to move-out date if not set.', null=True, verbose_name='Contract end date'),
        ),
        migrations.AddField(
            model_name='renter',
            name='contract_start_date',
            field=models.DateField(blank=True, help_text='Start date of the rental contract. Defaults to move-in date if not set.', null=True, verbose_name='Contract start date'),
        ),
        migrations.RunPython(set_contract_dates_from_move_dates, reverse_contract_dates),
    ]
