# Generated by Django 5.2.9 on 2026-01-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0027_add_contract_dates_to_renter'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='show_in_tax_overview',
            field=models.BooleanField(default=True, help_text='If checked, this bill will appear in the tax overview for the landlord.', verbose_name='Show in tax overview'),
        ),
    ]
