# Generated by Django 5.2.9 on 2026-01-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0028_add_show_in_tax_overview_to_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenterNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Überschrift des Hinweises', max_length=100, verbose_name='Title')),
                ('body', models.TextField(help_text='Inhalt des Hinweises (Markdown erlaubt)', verbose_name='Body')),
                ('billing_year', models.PositiveIntegerField(help_text='Jahr für das dieser Hinweis angezeigt werden soll', verbose_name='Billing Year')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('renters', models.ManyToManyField(help_text='Mieter für die dieser Hinweis gilt', related_name='notices', to='bill.renter', verbose_name='Renters')),
            ],
            options={
                'verbose_name': 'Renter Notice',
                'verbose_name_plural': 'Renter Notices',
                'ordering': ['-billing_year', 'title'],
            },
        ),
    ]
