# Generated by Django 5.2.9 on 2026-02-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0029_renter_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heatinginfo',
            name='hot_water_m3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Hot water m3'),
        ),
    ]
