# Generated by Django 5.2.9 on 2026-02-01 10:58

from django.db import migrations, models


def set_existing_to_sent(apps, schema_editor):
    HeatingInfo = apps.get_model('bill', 'HeatingInfo')
    HeatingInfo.objects.all().update(sent=True)


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0030_hot_water_m3_decimal_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatinginfo',
            name='sent',
            field=models.BooleanField(default=False, verbose_name='Sent'),
        ),
        migrations.RunPython(set_existing_to_sent, migrations.RunPython.noop),
    ]
