# Generated by Django 5.2.9 on 2026-02-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0031_add_sent_to_heatinginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='renter',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
