# Generated by Django 5.2.9 on 2026-02-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0032_add_email_to_renter'),
    ]

    operations = [
        migrations.AddField(
            model_name='renter',
            name='deposit_account',
            field=models.CharField(blank=True, max_length=34, null=True, verbose_name='Deposit account number'),
        ),
        migrations.AddField(
            model_name='renter',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Deposit amount'),
        ),
        migrations.AddField(
            model_name='renter',
            name='emergency_contact_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Emergency contact address'),
        ),
        migrations.AddField(
            model_name='renter',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Emergency contact name'),
        ),
        migrations.AddField(
            model_name='renter',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Emergency contact phone'),
        ),
        migrations.AddField(
            model_name='renter',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Relationship to renter'),
        ),
        migrations.AddField(
            model_name='renter',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone'),
        ),
    ]
