# Generated by Django 5.2.9 on 2026-02-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0033_add_contact_and_deposit_to_renter'),
    ]

    operations = [
        migrations.AddField(
            model_name='renter',
            name='additional_contact_info',
            field=models.TextField(blank=True, null=True, verbose_name='Additional contact info'),
        ),
    ]
