# Generated by Django 5.2.9 on 2026-02-02 10:49

import bill.models.renter
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0034_add_additional_contact_info_to_renter'),
    ]

    operations = [
        migrations.AddField(
            model_name='renter',
            name='token',
            field=models.CharField(default=bill.models.renter.generate_renter_token, editable=False, help_text='Token for external access to documents without login.', max_length=32, verbose_name='Access Token'),
        ),
    ]
