# Generated by Django 5.2.9 on 2026-02-02 10:50

from django.db import migrations
import secrets
import string


def generate_token():
    """Generiert einen zufälligen 32-Zeichen Token (a-zA-Z0-9)."""
    alphabet = string.ascii_letters + string.digits
    return ''.join(secrets.choice(alphabet) for _ in range(32))


def regenerate_tokens(apps, schema_editor):
    """Generiert für jeden Mieter einen eindeutigen Token."""
    Renter = apps.get_model('bill', 'Renter')
    for renter in Renter.objects.all():
        renter.token = generate_token()
        renter.save(update_fields=['token'])


def noop(apps, schema_editor):
    """Keine Rückwärts-Migration nötig."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0035_add_renter_token'),
    ]

    operations = [
        migrations.RunPython(regenerate_tokens, noop),
    ]
