# Generated by Django 5.2.9 on 2026-02-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0036_regenerate_unique_renter_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='renter',
            name='wants_heating_info',
            field=models.BooleanField(default=True, help_text='Whether the renter wants to receive monthly heating information.', verbose_name='Wants heating info'),
        ),
    ]
