# Generated by Django 5.2.9 on 2026-02-02 11:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0037_add_renter_wants_heating_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='renter',
            name='token_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When the access token was last updated.', verbose_name='Token updated at'),
        ),
    ]
