"""
Django settings for librelandlord project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-91hd@)ha9oci=67*n3v^p%lai%8(t4t27iz@a)ey81pfi+4b$#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.environ.get(
    'ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# OIDC Configuration - Environment based
USE_OIDC_ONLY = os.environ.get('USE_OIDC_ONLY', 'False').lower() == 'true'

HEATING_INFO_FOOTER = "Für Fragen oder wenn Daten nicht plausibel sind, wenden Sie sich bitte an Ihren Vermieter: Sven Anders, Neehusenstaße 11a, 21147 Hamburg, 040-2004297"

# Application definition

INSTALLED_APPS = [
    'bill.apps.BillConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mozilla_django_oidc',
]

MIDDLEWARE = [
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'librelandlord.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'librelandlord.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Environment-dependent database configuration
DATABASE_ENGINE = os.environ.get(
    'DATABASE_ENGINE', 'django.db.backends.sqlite3')


def get_database_password():
    """Get database password from environment or Docker secret file"""
    password_file = os.environ.get('DATABASE_PASSWORD_FILE')
    if password_file and os.path.exists(password_file):
        with open(password_file, 'r') as f:
            return f.read().strip()
    return os.environ.get('DATABASE_PASSWORD', '')


if DATABASE_ENGINE == 'django.db.backends.mysql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.environ.get('DATABASE_NAME', 'librelandlord'),
            'USER': os.environ.get('DATABASE_USER', 'librelandlord'),
            'PASSWORD': get_database_password(),
            'HOST': os.environ.get('DATABASE_HOST', 'localhost'),
            'PORT': os.environ.get('DATABASE_PORT', '3306'),
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                'charset': 'utf8mb4',
            },
        }
    }
else:
    # Default SQLite configuration
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'de'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Directories where Django will search for static files
STATICFILES_DIRS = []

# Directory where collected static files will be stored
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Verfügbare Sprachen (Beispiele)
LANGUAGES = [
    ('en', 'English'),
    ('de', 'Deutsch'),
    # Weitere Sprachen hinzufügen
]
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# Authentication Backends - Environment dependent
if USE_OIDC_ONLY:
    # Production: OIDC only
    AUTHENTICATION_BACKENDS = [
        'mozilla_django_oidc.auth.OIDCAuthenticationBackend',
    ]
else:
    # Demo/Development: Local users + OIDC (optional)
    AUTHENTICATION_BACKENDS = [
        'mozilla_django_oidc.auth.OIDCAuthenticationBackend',
        'django.contrib.auth.backends.ModelBackend',
    ]

# OIDC Settings for Keycloak
if 'mozilla_django_oidc' in INSTALLED_APPS:
    OIDC_RP_CLIENT_ID = os.environ.get(
        'OIDC_CLIENT_ID', 'librelandlord-django')
    OIDC_RP_CLIENT_SECRET = os.environ.get('OIDC_CLIENT_SECRET', '')

    # Keycloak endpoints - adjust to your setup
    KEYCLOAK_SERVER = os.environ.get(
        'KEYCLOAK_SERVER', 'https://your-keycloak-server.com')
    KEYCLOAK_REALM = os.environ.get('KEYCLOAK_REALM', 'librelandlord')

    OIDC_OP_AUTHORIZATION_ENDPOINT = f'{KEYCLOAK_SERVER}/keycloak/realms/{KEYCLOAK_REALM}/protocol/openid-connect/auth'
    OIDC_OP_TOKEN_ENDPOINT = f'{KEYCLOAK_SERVER}/keycloak/realms/{KEYCLOAK_REALM}/protocol/openid-connect/token'
    OIDC_OP_USER_ENDPOINT = f'{KEYCLOAK_SERVER}/keycloak/realms/{KEYCLOAK_REALM}/protocol/openid-connect/userinfo'
    OIDC_OP_JWKS_ENDPOINT = f'{KEYCLOAK_SERVER}/keycloak/realms/{KEYCLOAK_REALM}/protocol/openid-connect/certs'

    # OIDC Redirect URI - must use HTTPS in production
    OIDC_RP_USE_HTTPS = not DEBUG
    OIDC_RP_SIGN_ALGO = 'RS256'
    OIDC_RP_SCOPES = 'openid profile email'

    # Redirect URLs
    LOGIN_REDIRECT_URL = '/bill/'
    LOGOUT_REDIRECT_URL = '/'

    # Django Login URLs - redirect to OIDC
    LOGIN_URL = '/oidc/authenticate/'

    # Create users automatically from OIDC
    OIDC_CREATE_USER = True

    # Custom user info claims mapping
    def oidc_username_algo(email):
        return email.split('@')[0]

    OIDC_USERNAME_ALGO = oidc_username_algo

    # Verify SSL certificates (disable only for development)
    OIDC_VERIFY_SSL = not DEBUG
